#!/usr/bin/env bash
server {
    listen 80;
    server_name 52.86.154.94 34.239.253.222;

    location /airbnb-onepage/ {
        include proxy_params;
	proxy_pass http://localhost:5000/airbnb-onepage/;
    }

    location /airbnb-dynamic/number_odd_or_even/ {
        rewrite /airbnb-dynamic/(.*) $1 break;
        include proxy_params;
	proxy_pass http://localhost:5001/;
    }

    location /api/ {
        include proxy_params;
	proxy_pass http://localhost:5002/api/;
    }

    location / {
        include proxy_params;
	proxy_pass http://localhost:5003/;
    }
}
